In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

[Exercise](https://pythonai211225-rgb.github.io/python_libs/lessons/06_lesson/index.html#topic-10)

## Task 1
Setup & data: Load the file with df = pd.read_csv('Churn_Modelling.csv').  
Display the first 7 rows, then print df.shape and df.columns

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
display(df.head(7))
print()

print(df.shape)
print()

print(df.columns)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0

(10000, 14)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

## Task 2
Sorting: Sort customers by CreditScore from lowest to highest and show the first 7 rows

In [3]:
df.sort_values('CreditScore', ascending=True).head(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8762,8763,15765173,Lin,350,France,Female,60,3,0.00,1,0,0,113796.15,1
8723,8724,15803202,Onyekachi,350,France,Male,51,10,0.00,1,1,1,125823.79,1
1838,1839,15758813,Campbell,350,Germany,Male,39,0,109733.20,2,0,0,123602.11,1
9624,9625,15668309,Maslow,350,France,Female,40,0,111098.85,1,1,1,172321.21,1
1631,1632,15685372,Azubuike,350,Spain,Male,54,1,152677.48,1,1,1,191973.49,1
2473,2474,15679249,Chou,351,Germany,Female,57,4,163146.46,1,1,0,169621.69,1
1962,1963,15692416,Aikenhead,358,Spain,Female,52,8,143542.36,3,1,0,141959.11,1

## Task 3
Multi-column sorting: Sort by Geography ascending and Balance descending.  
Show the first 12 rows and explain what the two sort directions mean

In [4]:
df.sort_values(by=['Geography', 'Balance'], ascending=[True, False]).head(12)
#ascending=True means values are rising from minimum to maximum values
#ascending=False means values are falling from maximum to minimum values

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
1533,1534,15769818,Moore,850,France,Female,37,3,212778.20,1,0,1,69372.88,0
2709,2710,15780212,Mao,592,France,Male,37,4,212692.97,1,0,0,176395.02,0
8702,8703,15690589,Udinesi,541,France,Male,37,9,212314.03,1,0,1,148814.54,0
520,521,15671256,Macartney,850,France,Female,35,1,211774.31,1,1,0,188574.12,1
7353,7354,15736420,Macdonald,596,France,Male,21,4,210433.08,2,0,1,197297.77,1
5871,5872,15709920,Burke,479,France,Female,33,2,208165.53,1,0,0,50774.81,1
8982,8983,15627971,Coates,504,France,Female,32,8,206663.75,1,0,0,16281.94,0
6913,6914,15784180,Ku,564,France,Female,36,7,206329.65,1,1,1,46632.87,1
4436,4437,15664498,Golovanov,508,France,Male,26,7,205962.00,1,1,0,156424.40,0
9920,9921,15673020,Smith,678,France,Female,49,3,204510.94,1,0,1,738.88,1
6271,6272,15620756,Stokes,747,France,Male,49,6,202904.64,1,1,1,17298.72,1

## Task 4
Counts: Use value_counts() to count customers by Geography.  
Then count each Geography + Gender combination

In [5]:
# Solution 1
df.value_counts(['Geography'])
df.value_counts(['Geography', 'Gender'])

# Solution 2
display(df['Geography'].value_counts())
print()
display(df[['Geography', 'Gender']].value_counts())

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

Geography  Gender
France     Male      2753
           Female    2261
Spain      Male      1388
Germany    Male      1316
           Female    1193
Spain      Female    1089
Name: count, dtype: int64

## Task 5
Unique values: Show the unique values in Geography, Gender, NumOfProducts, and Exited.  
Then use nunique() to count how many different values each of these columns has

In [16]:
print(df['Geography'].unique())
print(df['Gender'].unique())
print(df['NumOfProducts'].unique())
print(df['Exited'].unique())

print(df['Geography'].nunique())
print(df['Gender'].nunique())
print(df['NumOfProducts'].nunique())
print(df['Exited'].nunique())

# Gemini cleaner solution
#target_cols = ['Geography', 'Gender', 'NumOfProducts', 'Exited']
#summary_df = pd.DataFrame({
#    'Unique_Values': [df[col].unique() for col in target_cols],
#    'Count_Unique': [df[col].nunique() for col in target_cols]
#}, index=target_cols)

['France' 'Spain' 'Germany']
['Female' 'Male']
[1 3 2 4]
[1 0]
3
2
4
2

## Task 6
Replace & map: Create a copy of the DataFrame.  
In the copy, replace Female with F and Male with M using .replace().  
Then solve the same change with .map()

In [7]:
df2 = df.copy()
df2.replace(['Female', 'Male'], ['F', 'M'], inplace=True)

df2 = df.copy()
gender_map = {
    'Female': 'F',
    'Male': 'M'
}
df2['Gender'] = df2['Gender'].map(gender_map)
df2

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,F,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,F,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,F,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,F,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,F,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,M,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,M,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,F,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,M,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,F,28,4,130142.79,1,1,0,38190.78,0

## Task 7
Top & lowest values: Find the 6 customers with the highest Balance using nlargest.  
Then find the 4 customers with the lowest CreditScore using nsmallest

In [8]:
df.nlargest(6, 'Balance')

df.nsmallest(4, 'CreditScore')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1631,1632,15685372,Azubuike,350,Spain,Male,54,1,152677.48,1,1,1,191973.49,1
1838,1839,15758813,Campbell,350,Germany,Male,39,0,109733.20,2,0,0,123602.11,1
8723,8724,15803202,Onyekachi,350,France,Male,51,10,0.00,1,1,1,125823.79,1
8762,8763,15765173,Lin,350,France,Female,60,3,0.00,1,0,0,113796.15,1

## Task 8
sample(): Show 9 random customers using sample(9).  
Then show a 3% random sample using sample(frac=0.03)

In [9]:
df.sample(9)
df.sample(frac=0.03)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3822,3823,15626985,Yefremova,850,France,Female,39,0,104386.53,1,1,0,105886.77,0
1051,1052,15715003,Ko,625,Spain,Female,49,2,80816.45,1,1,1,20018.79,0
2488,2489,15571148,Baranov,645,Spain,Female,21,1,0.00,2,0,0,28726.07,0
4956,4957,15628420,Alekseeva,660,Spain,Male,33,2,80462.24,1,0,0,150422.35,0
8692,8693,15755138,Chin,850,France,Female,32,8,0.00,2,1,1,55593.80,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7970,7971,15577398,Ch'eng,850,France,Male,30,6,86449.39,1,1,1,188809.23,0
9099,9100,15768881,Saunders,738,France,Male,29,2,0.00,2,1,1,170421.13,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
644,645,15698786,Marcelo,819,France,Female,39,9,133102.92,1,1,0,27046.46,1
9086,9087,15743545,Nworie,647,Spain,Female,29,2,0.00,2,1,0,179032.68,0

## Task 9
Duplicates: Check whether the dataset has duplicated CustomerId values.  
Then use sorting plus drop_duplicates('Geography') to keep one customer per country with the highest Balance

In [10]:
# Total number of duplicate Customer IDs
df['CustomerId'].duplicated().sum()

df.sort_values(['Balance'], ascending=False).drop_duplicates('Geography')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2092,2093,15757408,Lo,655,Spain,Male,38,3,250898.09,3,0,1,81054.00,1
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
1067,1068,15599131,Dilke,650,Germany,Male,26,4,214346.96,2,1,0,128815.33,0

## Task 10
Largest values plus unique values: Find the 12 customers with the highest EstimatedSalary.  
From those rows, print the unique Geography values

In [11]:
df.nlargest(12, 'EstimatedSalary')
df.nlargest(12, 'EstimatedSalary')['Geography'].unique()

array(['Spain', 'Germany', 'France'], dtype=object)

## Task 11
Missing data: Use the DataFrame below and implement the requested cleaning operations

> df_missing = pd.DataFrame({  
>    'A': [None, 2, 3, None, 5, None],  
>    'B': [10, None, None, 40, 50, None],  
>    'C': [100, None, 300, 400, None, None]  
>})  

| Index | A | B | C |
| --- | --- | --- | --- |
| 0 | NaN | 10.0 | 100.0 |
| 1 | 2.0 | NaN | NaN |
| 2 | 3.0 | NaN | 300.0 |
| 3 | NaN | 40.0 | 400.0 |
| 4 | 5.0 | 50.0 | NaN |
| 5 | NaN | NaN | NaN |


1. Eliminate any row in the DataFrame that contains at least one NaN value
2. Modify the previous task and eliminate only rows that have NaN values across all columns
3. Eliminate rows that have at least one NaN in columns A and C only
4. Replace all NaN values with a specified value of your choice
5. Replace all NaN values in column B with the mean of the non-NaN values in that column

In [12]:
df_missing = pd.DataFrame({
'A': [None, 2, 3, None, 5, None],
'B': [10, None, None, 40, 50, None],
'C': [100, None, 300, 400, None, None]
})

# 1
df_missing.dropna()

# 2
df_missing.dropna(thresh=1)

# 3
df_missing.dropna(subset=['A', 'C'])

# 4
df_missing.fillna('Chocolate')

# 5
df_missing['B'].fillna(df_missing['B'].mean())

0    10.000000
1    33.333333
2    33.333333
3    40.000000
4    50.000000
5    33.333333
Name: B, dtype: float64