In [1]:
import numpy as np
import pandas as pd

[Exercise](https://pythonai211225-rgb.github.io/python_libs/lessons/07_lesson/index.html#topic-10)

## Task 1
Load tips.csv. Display the first rows, df.info(), and df.describe().T  
Then add a new column price_per_person calculated as total_bill / size.

In [2]:
tips_df = pd.read_csv('tips.csv')
df = tips_df.copy()

display(df.head())
display(df.info())
display(df.describe().T)

def p_per_p(total_bill, size):
    return (total_bill / size)
    
df['price_per_person'] = np.vectorize(p_per_p)(
    df['total_bill'],
    df['size']
)
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    str
 3   smoker            244 non-null    str
 4   day               244 non-null    str
 5   time              244 non-null    str
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    str
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    str
dtypes: float64(3), int64(2), str(6)
memory usage: 21.1 KB

None

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.676667,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,Michelle Hardin,3511451626698139,Thur672

## Task 2
Count how many orders (rows) were placed at each time and for each gender.

In [3]:
df.groupby(['time', 'sex'])['total_bill'].count().rename('total_orders')

time    sex
Dinner  Female     52
        Male      124
Lunch   Female     35
        Male       33
Name: total_orders, dtype: int64

## Task 3
Count how many orders (rows) were placed on each day.

In [4]:
df.groupby(['day'])['total_bill'].count().rename('total_orders_per_day')

day
Fri     19
Sat     87
Sun     76
Thur    62
Name: total_orders_per_day, dtype: int64

## Task 4
Find the maximum price_per_person for each day and gender combination.

In [5]:
df.groupby(['day', 'sex'])['price_per_person'].max()

day   sex
Fri   Female    11.375000
      Male      14.485000
Sat   Female    14.766667
      Male      16.936667
Sun   Female     8.815000
      Male      20.275000
Thur  Female    10.777500
      Male      16.340000
Name: price_per_person, dtype: float64

## Task 5
Find the minimum price_per_person for each day and size combination.

In [6]:
df.groupby(['day', 'size'])['price_per_person'].min()

day   size
Fri   1        8.580000
      2        2.875000
      3        5.326667
      4       10.042500
Sat   1        3.070000
      2        3.870000
      3        5.230000
      4        4.452500
      5        5.630000
Sun   2        3.625000
      3        3.443333
      4        4.122500
      5        4.138000
      6        8.028333
Thur  1       10.070000
      2        3.755000
      3        5.490000
      4        5.132500
      5        8.238000
      6        4.508333
Name: price_per_person, dtype: float64

## Task 6
Calculate the sum of total_bill grouped by size and smoker status.  
Then use .loc to extract the sum for size 2 smokers only.

In [7]:
df.groupby(['size', 'smoker'])['total_bill'].sum()

df.groupby(['size', 'smoker'])['total_bill'].sum().loc[(2, 'Yes')]

np.float64(1185.08)

## Task 7
Display the maximum price_per_person grouped by day and gender  
Then use .loc to show the results for Male only across all days.

In [9]:
df.groupby(['day', 'sex'])['price_per_person'].max()

df.groupby(['sex', 'day'])['price_per_person'].max().loc[('Male')]

# alternative answer
df.groupby(['day', 'sex'])['price_per_person'].max().xs('Male', level='sex')

day
Fri     14.485000
Sat     16.936667
Sun     20.275000
Thur    16.340000
Name: price_per_person, dtype: float64